x-crypto:
  &crypto
  cap_drop:
    - all
  cap_add:
    - chown
    - setuid
    - setgid
    - sys_admin
    - mknod
  security_opt:
    - apparmor=unconfined
    - seccomp=unconfined

services:
  cont_nim:
    << : *crypto
    container_name: continuous-nim
    build : .
    ports :
        - "19600:5000"
