FROM python:3.11.3-bullseye

WORKDIR /app
COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

ENV FLAG "grey{r3d1recTs_r3Dir3cts_4nd_4ll_0f_th3_r3d1r3ct5}"
ENV ADMIN_COOKIE "36f5337b363272a56699f8759fbd1998c7bd84aa69ab57fde20cc9921b4782a4"

COPY . .

EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--threads", "4", "app:app"]