x-crypto:
    &crypto
    cap_drop:
      - all
    cap_add:
      - chown
      - setuid
      - setgid
      - sys_admin
      - mknod
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined

services:
    ot:
        << : *crypto
        build : .
        ports :
            - "10521:5000"